spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/unknown?createDatabaseIfNotExist=true
    username: root
    password: mario
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect