spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/TimeAndAttendanceSystem?createDatabaseIfNotExist=true
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect